# Generated by Django 4.1.7 on 2023-03-02 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial number')),
                ('model', models.CharField(choices=[('LW', 'Lightweight'), ('MW', 'Middleweight'), ('CW', 'Cruiserweight'), ('HW', 'Heavyweight')], default='LW', max_length=2)),
                ('weight_limit', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Weight limit (grams)')),
                ('battery_capacity', models.FloatField(help_text='Range from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Battery capacity (percentage)')),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=10)),
            ],
            options={
                'verbose_name': 'drone',
                'verbose_name_plural': 'drones',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\-\\_]*$')])),
                ('weight', models.FloatField(help_text='In grams')),
                ('code', models.TextField(validators=[django.core.validators.RegexValidator('^[A-Z0-9\\_]*$')])),
                ('image', models.ImageField(upload_to='uploads/medications/%Y/%m/%d/')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='main.drone')),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
            },
        ),
    ]
