# Generated by Django 4.1.7 on 2023-03-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_drone_weight_limit_alter_medication_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='main.drone'),
        ),
    ]
