# Generated by Django 4.1.7 on 2023-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_medication_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/medications/%Y/%m/%d/'),
        ),
    ]
